package generator

var PewpewEnums = map[string]map[string]string {
	"MothershipType": {
		"Triangle": "THREE_CORNERS",
		"Square": "FOUR_CORNERS",
		"Pentagon": "FIVE_CORNERS",
		"Hexagon": "SIX_CORNERS",
		"Heptagon": "SEVEN_CORNERS",
	},
	"EntityType": {
		"Asteroid": "ASTEROID",
		"YellowBaf": "BAF",
		"Inertiac": "INERTIAC",
		"Mothership": "MOTHERSHIP",
		"MothershipBullet": "MOTHERSHIP_BULLET",
		"RollingCube": "ROLLING_CUBE",
		"RollingSphere": "ROLLING_SPHERE",
		"Ufo": "UFO",
		"Wary": "WARY",
		"Crowder": "CROWDER",
		"CustomizableEntity": "CUSTOMIZABLE_ENTITY",
		"Ship": "SHIP",
		"Bomb": "BOMB",
		"BlueBaf": "BAF_BLUE",
		"RedBaf": "BAF_RED",
		"WaryMissile": "WARY_MISSILE",
		"UfoBullet": "UFO_BULLET",
		"PlayerBullet": "PLAYER_BULLET",
		"BombExplosion": "BOMB_EXPLOSION",
		"PlayerExplosion": "PLAYER_EXPLOSION",
		"Bonus": "BONUS",
		"FloatingMessage": "FLOATING_MESSAGE",
		"Pointonium": "POINTONIUM",
		"BonusImplosion": "BONUS_IMPLOSION",
	},
	"CannonType": {
		"Single": "SINGLE",
		"TicToc": "TIC_TOC",
		"Double": "DOUBLE",
		"Triple": "TRIPLE",
		"FourDirections": "FOUR_DIRECTIONS",
		"DoubleSwipe": "DOUBLE_SWIPE",
		"Hemisphere": "HEMISPHERE",
	},
	"CannonFreq": {
		"Freq30": "FREQ_30",
		"Freq15": "FREQ_15",
		"Freq10": "FREQ_10",
		"Freq7_5": "FREQ_7_5",
		"Freq6": "FREQ_6",
		"Freq5": "FREQ_5",
		"Freq3": "FREQ_3",
		"Freq2": "FREQ_2",
		"Freq1": "FREQ_1",
	},
	"BombType": {
		"Freeze": "FREEZE",
		"Repulsive": "REPULSIVE",
		"Atomize": "ATOMIZE",
		"SmallAtomize" : "SMALL_ATOMIZE",
		"SmallFreeze": "SMALL_ATOMIZE",
	},
	"WeaponType": {
		"Bullet": "BULLET",
		"FreezeExplosion": "FREEZE_EXPLOSION",
		"RepulsiveExplosion": "REPULSIVE_EXPLOSION",
		"AtomizeExplosion": "ATOMIZE_EXPLOSION",
	},
	"AsteroidSize": {
		"S": "SMALL",
		"M": "MEDIUM",
		"L": "LARGE",
		"XL": "VERY_LARGE",
	},
}

var PewpewVariables = map[string]string{
	"Print": "print",
	"PrintDebug": "print_debug_info",
	"SetLevelSize": "set_level_size",
	"AddWall": "add_wall",
	"RemoveWall": "remove_wall",
	"AddUpdateCallback": "add_update_callback",
	"GetNumberOfPlayers": "get_number_of_players",
	"IncreasePlayerScore": "increase_score_of_player",
	"IncreasePlayerScoreStreak": "increase_score_streak_of_player",
	"GetPlayerScoreStreak": "get_score_streak_level",
	"StopGame": "stop_game",
	"GetPlayerInputs": "get_player_inputs",
	"GetPlayerScore": "get_score_of_player",
	"ConfigurePlayer": "configure_player",
	"ConfigurePlayerHud": "configure_player_hud",
	"GetPlayerConfig": "get_player_configuration", 
	"ConfigureShipWeapon": "configure_player_ship_weapon",
	"DamageShip": "add_damage_to_player_ship",
	"AddArrowToShip": "add_arrow_to_player_ship",
	"RemoveArrowFromShip": "remove_arrow_from_player_ship", 
	"SetShipSpeed": "set_player_ship_speed",
	"MakeShipTransparent": "make_player_ship_transparent",  
	"GetAllEntities": "get_all_entities",
	"GetEntitiesInRadius": "get_entities_colliding_with_disk", 
	"GetEntityCount": "get_entity_count",
	"GetEntityType": "get_entity_type",
	"GetEntitiesCollidingWithDisk": "get_entities_colliding_with_disk",
	"CreateExplosion": "create_explosion",
	"NewAsteroid": "new_asteroid",
	"NewAsteroidWithSize": "new_asteroid_with_size", 
	"NewYellowBaf": "new_baf",
	"NewRedBaf": "new_baf_red",
	"NewBlueBaf": "new_baf_blue",
	"NewBomb": "new_bomb",
	"NewBonus": "new_bonus",
	"NewCrowder": "new_crowder",
	"NewFloatingMessage": "new_floating_message",
	"NewEntity": "new_customizable_entity",
	"NewInertiac": "new_inertiac",
	"NewMothership": "new_mothership",
	"NewPointonium": "new_pointonium",
	"NewShip": "new_player_ship",
	"NewBullet": "new_player_bullet",
	"NewRollingCube": "new_rolling_cube",
	"NewRollingSphere": "new_rolling_sphere",
	"NewWary": "new_wary",
	"NewUfo": "new_ufo",
	"SetRollingCubeWallCollision": "rolling_cube_set_enable_collisions_with_walls",
	"SetUFOWallCollision": "ufo_set_enable_collisions_with_walls",
	"GetEntityPosition": "entity_get_position",
	"IsEntityAlive": "entity_get_is_alive",
	"IsEntityBeingDestroyed": "entity_get_is_started_to_be_destroyed",
	"SetEntityPosition": "entity_set_position",
	"SetEntityRadius": "entity_set_radius",
	"SetEntityMesh": "customizable_entity_set_mesh",
	"SetEntityCallback": "entity_set_update_callback",
	"DestroyEntity": "entity_destroy",
	"EntityReactToWeapon": "entity_react_to_weapon",
	"PlayAmbientSound": "play_ambient_sound",
	"PlaySound": "play_sound",
	"SetEntityColor": "customizable_entity_set_mesh_color",
	"SetEntityFlippingMeshes": "customizable_entity_set_flipping_meshes",
	"SetEntityInterpolation": "customizable_entity_set_position_interpolation",
	"EntitySkipAttributesInterpolation": "customizable_entity_skip_mesh_attributes_interpolation",
	"SetEntityString": "customizable_entity_set_string",
	"SetEntityMeshPosition": "customizable_entity_set_mesh_xyz",
	"SetEntityMeshScale": "customizable_entity_set_mesh_scale",
	"SetEntityMeshScaleXYZ": "customizable_entity_set_mesh_xyz_scale",
	"SetEntityMeshAngle": "customizable_entity_set_mesh_angle",
	"ConfigureEntityMusicResponce": "customizable_entity_configure_music_response",
	"RotateEntityMesh": "customizable_entity_add_rotation_to_mesh",
	"SetEntityVisibilityRadius": "customizable_entity_set_visibility_radius",
	"ConfigureEntityWallCollision": "customizable_entity_configure_wall_collision",
	"SetEntityWallCollision":"customizable_entity_configure_wall_collision",
	"SetEntityPlayerCollision": "customizable_entity_set_player_collision_callback",
	"SetEntityWeaponCollision": "customizable_entity_set_weapon_collision_callback",
	"SpawnEntity": "customizable_entity_start_spawning",
	"ExplodeEntity": "customizable_entity_start_exploding",

	"MothershipType": "MothershipType",
	"CannonFreq": "CannonFrequency",
	"EntityType": "EntityType",
	"CannonType": "CannonType",
	"BombType": "BombType",
	"WeaponType": "WeaponType",
	"AsteroidSize": "AsteroidSize",
}
