// Code generated by "stringer -type=TokenType -linecomment"; DO NOT EDIT.

package tokens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Hash-0]
	_ = x[LeftParen-1]
	_ = x[RightParen-2]
	_ = x[LeftBrace-3]
	_ = x[RightBrace-4]
	_ = x[LeftBracket-5]
	_ = x[RightBracket-6]
	_ = x[Comma-7]
	_ = x[At-8]
	_ = x[Pipe-9]
	_ = x[Colon-10]
	_ = x[SemiColon-11]
	_ = x[Dot-12]
	_ = x[Concat-13]
	_ = x[Ellipsis-14]
	_ = x[Minus-15]
	_ = x[MinusEqual-16]
	_ = x[Plus-17]
	_ = x[PlusEqual-18]
	_ = x[Slash-19]
	_ = x[SlashEqual-20]
	_ = x[BackSlash-21]
	_ = x[BackSlashEqual-22]
	_ = x[Star-23]
	_ = x[StarEqual-24]
	_ = x[Caret-25]
	_ = x[CaretEqual-26]
	_ = x[Bang-27]
	_ = x[BangEqual-28]
	_ = x[Equal-29]
	_ = x[EqualEqual-30]
	_ = x[FatArrow-31]
	_ = x[ThinArrow-32]
	_ = x[Greater-33]
	_ = x[GreaterEqual-34]
	_ = x[Less-35]
	_ = x[LessEqual-36]
	_ = x[Modulo-37]
	_ = x[ModuloEqual-38]
	_ = x[Degree-39]
	_ = x[Fixed-40]
	_ = x[FixedPoint-41]
	_ = x[Identifier-42]
	_ = x[Number-43]
	_ = x[Radian-44]
	_ = x[String-45]
	_ = x[Is-46]
	_ = x[Isnt-47]
	_ = x[Alias-48]
	_ = x[And-49]
	_ = x[As-50]
	_ = x[Break-51]
	_ = x[By-52]
	_ = x[Const-53]
	_ = x[Continue-54]
	_ = x[Else-55]
	_ = x[Entity-56]
	_ = x[Enum-57]
	_ = x[Env-58]
	_ = x[False-59]
	_ = x[Find-60]
	_ = x[Fn-61]
	_ = x[For-62]
	_ = x[If-63]
	_ = x[In-64]
	_ = x[From-65]
	_ = x[To-66]
	_ = x[Let-67]
	_ = x[Macro-68]
	_ = x[Match-69]
	_ = x[New-70]
	_ = x[Or-71]
	_ = x[Pub-72]
	_ = x[Repeat-73]
	_ = x[Return-74]
	_ = x[Self-75]
	_ = x[Spawn-76]
	_ = x[Struct-77]
	_ = x[Class-78]
	_ = x[Tick-79]
	_ = x[True-80]
	_ = x[Use-81]
	_ = x[While-82]
	_ = x[With-83]
	_ = x[Yield-84]
	_ = x[Destroy-85]
	_ = x[Eof-86]
}

const _TokenType_name = "#(){}[],@|:;......--=++=//=\\\\=**=^^=!!=====>->>>=<<=%%=degreefixedfixedPointidentifiernumberradianstringisisntaliasandasbreakbyconstcontinueelseentityenumenvfalsefindfnforifinfromtoletmacromatchneworpubrepeatreturnselfspawnstructclassticktrueusewhilewithyielddestroyEOF (End of File)"

var _TokenType_index = [...]uint16{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 18, 19, 21, 22, 24, 25, 27, 28, 30, 31, 33, 34, 36, 37, 39, 40, 42, 44, 46, 47, 49, 50, 52, 53, 55, 61, 66, 76, 86, 92, 98, 104, 106, 110, 115, 118, 120, 125, 127, 132, 140, 144, 150, 154, 157, 162, 166, 168, 171, 173, 175, 179, 181, 184, 189, 194, 197, 199, 202, 208, 214, 218, 223, 229, 234, 238, 242, 245, 250, 254, 259, 266, 283}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
