package mapping

var MathVariables = map[string]string{
	"Pi":     "pi",
	"Huge":   "huge",
	"MaxInt": "maxinteger",
	"MinInt": "mininteger",
	"Abs":    "abs",
	"Acos":   "acos",
	"Atan":   "atan",
	"Ceil":   "ceil",
	"Floor":  "floor",
	"Cos":    "cos",
	"Sin":    "sin",
	"Sincos": "sincos",
	"Deg":    "deg",
	"Rad":    "rad",
	"Exp":    "exp",
	"ToInt":  "tointeger",
	"Fmod":   "fmod",
	"Ult":    "ult",
	"Log":    "log",
	"Max":    "max",
	"Min":    "min",
	"Modf":   "modf",
	"Random": "random",
	"Sqrt":   "sqrt",
	"Tan":    "tan",
	"Type":   "type",
}
